"""为系统角色名称增加唯一约束

Revision ID: 066390522b4a
Revises: 58e9af26beed
Create Date: 2026-07-23 14:23:23.137039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066390522b4a'
down_revision: Union[str, Sequence[str], None] = '58e9af26beed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    # ### end Alembic commands ###
