"""创建 Issue 评论与 Review 相关表

Revision ID: 1429d98ec07c
Revises: f5096068578d
Create Date: 2026-07-23 14:42:42.323425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1429d98ec07c'
down_revision: Union[str, Sequence[str], None] = 'f5096068578d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Issue 主键'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='所属项目'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False, comment='创建人'),
    sa.Column('assignee_id', sa.BigInteger(), nullable=True, comment='负责人'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Issue 标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='Issue 描述'),
    sa.Column('type', sa.String(length=30), server_default=sa.text("'TASK'"), nullable=False, comment='Issue 类型'),
    sa.Column('priority', sa.String(length=30), server_default=sa.text("'MEDIUM'"), nullable=False, comment='Issue 优先级'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'OPEN'"), nullable=False, comment='Issue 状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否已删除'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_issues_assignee_id_users')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name=op.f('fk_issues_creator_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_issues_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues')),
    comment='Issue 核心业务表'
    )
    op.create_index('idx_issues_assignee_id', 'issues', ['assignee_id'], unique=False)
    op.create_index('idx_issues_project_id', 'issues', ['project_id'], unique=False)
    op.create_index('idx_issues_project_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_index('idx_issues_status', 'issues', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='评论主键'),
    sa.Column('issue_id', sa.BigInteger(), nullable=False, comment='Issue 主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='评论用户'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_comments_issue_id_issues')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments')),
    comment='Issue 评论表'
    )
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Review 主键'),
    sa.Column('issue_id', sa.BigInteger(), nullable=False, comment='Issue 主键'),
    sa.Column('requester_id', sa.BigInteger(), nullable=False, comment='发起人'),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False, comment='审核人'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False, comment='审核状态'),
    sa.Column('comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_reviews_issue_id_issues')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_reviews_requester_id_users')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    comment='Issue Review 表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 删除数据表会由 MySQL 一并删除表内索引；显式先删外键支撑索引会失败。
    op.drop_table('reviews')
    op.drop_table('comments')
    op.drop_table('issues')
