"""创建用户权限相关表

Revision ID: 58e9af26beed
Revises: 
Create Date: 2026-07-23 10:34:18.489749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e9af26beed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='权限主键'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限唯一编码'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='权限说明'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code')),
    comment='系统权限表'
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='角色主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='角色说明'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    comment='系统角色表'
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='用户主键'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='用户邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像地址'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='账号是否启用'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否已删除'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    comment='系统用户表'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='关联记录主键'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色主键'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限主键'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_id_permission_id'),
    comment='角色权限关联表'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='关联记录主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户主键'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色主键'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles_user_id_role_id'),
    comment='用户角色关联表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
