"""创建站内通知表

Revision ID: 759adf3f87a8
Revises: 1429d98ec07c
Create Date: 2026-07-23 14:50:08.698630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759adf3f87a8'
down_revision: Union[str, Sequence[str], None] = '1429d98ec07c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='通知主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='接收用户'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='通知类型'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='关联对象类型'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='关联对象主键'),
    sa.Column('content', sa.Text(), nullable=False, comment='通知内容'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否已读'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    comment='站内通知表'
    )
    op.create_index('idx_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 删除表时由 MySQL 一并删除索引，避免先删除外键可用索引。
    op.drop_table('notifications')
