"""创建项目与项目成员相关表

Revision ID: f5096068578d
Revises: 066390522b4a
Create Date: 2026-07-23 14:35:20.551647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5096068578d'
down_revision: Union[str, Sequence[str], None] = '066390522b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='角色主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='项目角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='项目角色说明'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_project_roles_name')),
    comment='项目角色表'
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='项目主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'ACTIVE'"), nullable=False, comment='项目状态'),
    sa.Column('owner_id', sa.BigInteger(), nullable=False, comment='项目主负责人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='是否已删除'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    comment='研发项目表'
    )
    op.create_table('project_members',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='成员关系主键'),
    sa.Column('project_id', sa.BigInteger(), nullable=False, comment='项目主键'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户主键'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='项目角色主键'),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='加入项目时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects')),
    sa.ForeignKeyConstraint(['role_id'], ['project_roles.id'], name=op.f('fk_project_members_role_id_project_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_members_project_id_user_id'),
    comment='项目成员表'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_members')
    op.drop_table('projects')
    op.drop_table('project_roles')
    # ### end Alembic commands ###
