"""站内通知类型常量。"""

PROJECT_MEMBER_ADDED = "PROJECT_MEMBER_ADDED"
ISSUE_ASSIGNED = "ISSUE_ASSIGNED"
ISSUE_STATUS_CHANGED = "ISSUE_STATUS_CHANGED"
REVIEW_REQUESTED = "REVIEW_REQUESTED"
REVIEW_APPROVED = "REVIEW_APPROVED"
REVIEW_REJECTED = "REVIEW_REJECTED"
